version: 2
updates:
  # --- NPM (docs-interactive or any JS subfolders) ---
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 10
    labels: ["dependencies", "automerge-candidate", "javascript"]

  # --- Python (pip/pyproject) ---
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 10
    labels: ["dependencies", "automerge-candidate", "python"]

  # --- GitHub Actions versions ---
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 10
    labels: ["dependencies", "automerge-candidate", "ci"]

  # --- Dockerfiles (if present) ---
  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 10
    labels: ["dependencies", "automerge-candidate", "docker"]
