# prometheus.yml - Prometheus configuration for Nox monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nox-api'
    static_configs:
      - targets: ['api:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  - job_name: 'nox-dashboard'
    static_configs:
      - targets: ['dashboard:8501']
    metrics_path: '/_stcore/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
