apiVersion: v1
kind: ConfigMap
metadata:
  name: nox-api-config
  namespace: nox-api
data:
  # Application configuration
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  API_V7_URL: "https://api.example.com"
  FRONTEND_URL: "https://app.example.com"
  
  # Performance settings
  WORKER_COUNT: "4"
  MAX_CONNECTIONS: "100"
  POOL_SIZE: "20"
  
  # Feature flags
  PROMETHEUS_ENABLED: "true"
  METRICS_ENABLED: "true"
  
  # OAuth2 configuration
  OAUTH_CALLBACK_PATH: "/api/v7/auth/callback"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: nox-api
data:
  POSTGRES_DB: "noxdb"
  POSTGRES_HOST_AUTH_METHOD: "md5"
  PGDATA: "/var/lib/postgresql/data/pgdata"
