apiVersion: v1
kind: Namespace
metadata:
  name: nox-api
  labels:
    app.kubernetes.io/name: nox-api
    app.kubernetes.io/version: "7.0.0"
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nox-api-quota
  namespace: nox-api
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4" 
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: nox-api-limits
  namespace: nox-api
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
