# Prometheus Configuration for Nox API v7.0.0 Development
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nox-api-dev'
    static_configs:
      - targets: ['nox-api-dev:8082']
    metrics_path: '/api/v7/metrics/prometheus'
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
