name: Auto Label Pull Requests

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR from Dependabot
        if: github.actor == 'dependabot[bot]'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['dependencies']
            });

      - name: Label PRs with workflow changes
        if: contains(github.event.pull_request.title, 'workflow') || contains(github.event.pull_request.title, 'ci')
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['ci', 'workflow']
            });

      - name: Label Hygiene PRs
        if: contains(github.event.pull_request.title, 'hygiene')
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['hygiene', 'docs', 'triage']
            });
