name: Dependabot auto-merge
on:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge-candidate')
    runs-on: ubuntu-latest
    steps:
      - name: Merge Dependabot PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
