name: Dependabot auto-merge

on:
  pull_request_target:
    types: [labeled, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-automerge:
    # Only for Dependabot PRs that carry the label
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'automerge-candidate')
    runs-on: ubuntu-latest
    steps:
      - name: Enable PR auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
